### ISSUE TITLE
어디에서 검열이 된건지 조사 부탁드립니다!

### ISSUE THREAD

**Issue by litsyneko** [Tanat05/korcen#10]
**검열된 텍스트 메시지: **명조 35까지 1렙 남앗다
![Screenshot_20240604_145507_Discord](https://github.com/KR-korcen/korcen/assets/63511753/40c86698-6668-41b6-8edc-71bd84fce2e3)

**Comment by kdh8219** [comment]
`조 35까`부분으로 보입니다
https://github.com/Tanat05/korcen/blob/2cfdf9589f9dc6e27e4f90931ec9e0357cab4eca/korcen/korcen.py#L539-L540

**Comment by Tanat05** [comment]
https://github.com/Tanat05/korcen/blob/65e71a1ba798b5e0b4a8ec7002056beaa720501f/korcen/korcen.py#L520
