### ISSUE TITLE
discord.py 코드의 문제

### ISSUE THREAD

**Issue by keyfrog-21K** [Tanat05/korcen#4]
discord.py 코드 중
` await bot.process_commads(msg) `
msg 부분에 문제가 있습니다. 빨간 줄 쳐져요. pip 설치 등등 다 했습니다.
macOS 12에서 Python 3.9.4 쓰고 있구요, IDE는 Visual Studio Code 씁니다. 확인해주실 수 있나요?

**Comment by Tanat05** [comment]
msg를 message로 변경해보세요
해당 코드는 다른 명령어를 사용하기 위해 존재하는 부분으로 삭제하셔도 됩니다

**Comment by keyfrog-21K** [comment]
예, 감사합니당~
